# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('hallticketnumber', models.IntegerField()),
                ('date_of_join', models.DateField()),
                ('section', models.IntegerField()),
                ('branchname', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electrical & Electronics Engineering')], max_length=3)),
            ],
        ),
    ]
