# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='date_of_join',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
