# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='hallticketnumber',
            field=models.IntegerField(default=0),
        ),
    ]
