# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_studentdetails_hallticketnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='section',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='hallticketnumber',
            field=models.IntegerField(default=160114733000),
        ),
    ]
